### ISSUE TITLE
Disable Shared Folder (shares)

### ISSUE THREAD

**Issue by FilipQL** [UniSharp/laravel-filemanager#101]
Is there an option to disable shared folder (shares) in case if we _allow multi users_ ('allow_multi_user'      => true) but we don't want to have _shares_ folder?

**Comment by g0110280** [comment]
Haven't support this feature for now.
You can modify files in `/vendor/unisharp/laravel-filemanager/src/views/` to hide shares folder.

**Comment by FilipQL** [comment]
@g0110280  Ok, thanks! I just removed:

```
  <li style="margin-left: -10px;">
    <a class="pointer folder-item" data-id="{{ $share_dir }}">
      <i class="fa fa-folder"></i> {{ Lang::get('laravel-filemanager::lfm.title-shares') }}
    </a>
  </li>
```

from **tree.blade.php** and it seems that's all I have to do (for now).

**Comment by w0rd-driven** [comment]
You can also set the config option `shared_folder_name` to ''. When I did that, I changed the images_url to remove the trailing slash as it would make urls like files//directory. Due to the reuse of the function that handles this, I couldn't adequately get it to stop appending that extra /. I likely could if I had more time.

I think setting it to null or having it optional would be useful. When you click Back you can't go up to the parent directory with shares/ in it. I think shares makes sense under a multi user scenario but in my case with no multi users I'd rather there it default to having no shares folder and everything is just in the root.

**Comment by g0110280** [comment]
@w0rd-driven Thanks for your advice!
We might add your suggestion to v1.7.

**Comment by adteague** [comment]
Is there a new workaround for removing the shared folder?

**Comment by g0110280** [comment]
Please follow the [upgrade document](https://unisharp.github.io/laravel-filemanager/upgrade) and upgrade to `v1.7.1`.
