### ISSUE TITLE
filemanager redirects to /login page

### ISSUE THREAD

**Issue by blackLotus1998** [UniSharp/laravel-filemanager#1016]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system : Window 10
 * Laravel version : 6.20.7
 * Package version : 2.2

![image](https://user-images.githubusercontent.com/21292986/101536045-70029700-39d4-11eb-94bf-ef59089bfe27.png)

i using multi auth with 2 tables, how should i do to?

**Comment by blackLotus1998** [comment]
https://github.com/UniSharp/laravel-filemanager/issues/812
i saw this, and there is not solution

**Comment by JDsWebService** [comment]
If you're using multi auth i'm assuming that there are two different middlewares handling the two different auth methods right? The one that comes with Laravel is just `auth`... so whatever you have for your second middleware, make sure that you are changing the route middleware to include that one... for example...

For basic auth, that comes with laravel...

```
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
```

For my specific instance of admin authentication

```
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth.admin']], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
```
note the `auth.admin` instead of auth. should help clear things up.

**Comment by blackLotus1998** [comment]
finally working, thanks~

**Comment by mhdaouas** [comment]
I still don't understand the API naming convention of Laravel. I have under app/Controllers/AuthController.php a REST POST login() method, how can I reference it in the web.php Route::group... ?
