### ISSUE TITLE
Please help with my Laravel file manager invalid upload request

### ISSUE THREAD

**Issue by phengbird** [UniSharp/laravel-filemanager#1076]
Please help with my file manager invalid upload request , my storage linked , APP_URL changed

And provide the followings :
 * Operating system 

 * Laravel version : 8
 * Package version : 2.2
 * Steps to reproduce your issue : like can't go to thumbs
 * Screenshots of browser console :
![image](https://user-images.githubusercontent.com/39891579/124350262-35897180-dc26-11eb-8047-57b92dc990df.png)
![image](https://user-images.githubusercontent.com/39891579/124350279-5651c700-dc26-11eb-8135-0df64a38b1f2.png)

**Comment by SajjadAemmi** [comment]
you must enable GD library extension.

This is because the GD Library is missing on your server For **PHP 8.x**

Find your php.ini file, and then find the line:

```
;extension=gd
```
remove the semicolon in the front. ; means the line is commented, so remove the comment. The line should look like this:
```
extension=gd
```
Then restart apache and you are ready to go.

NOTE: If You are using **PHP <= 7.x**

```
;extension=php_gd2.dll
```
it should look like this: 
```
extension=php_gd2.dll
```
