### ISSUE TITLE
When send message image to email image not show

### ISSUE THREAD

**Issue by DilmurodQurbonboyev** [UniSharp/laravel-filemanager#1099]
Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system windows 10:
 * Laravel version 8.45:
 * Package version 2.2:
 * Steps to reproduce your issue  i send message using editor tinymce  to clients gmail address everything okay but image not show: 
 * Screenshots of browser console :
![Снимок](https://user-images.githubusercontent.com/75987687/137446445-87506773-ec4b-4998-bf33-a8e2fcc310c9.PNG)

**Comment by safarovitch** [comment]
Hey @DilmurodQurbonboyev,
I think this issue is not related to this package.
When sending images in email make sure you put your images in a trusted CDN or if the images are small in size, just put them as svg or embed them as base64.
Otherwise you images may be blocked by email providers.

Also as long as image path is correct, the image must show on email. Check for image path by inspecting email source code and make sure you are using right path in your email templates.

**Comment by DilmurodQurbonboyev** [comment]
thanks
