### ISSUE TITLE
Can't install on Laravel 10

### ISSUE THREAD

**Issue by rozpuh** [UniSharp/laravel-filemanager#1185]
Can't install on Laravel 10

**Comment by ilhamlutfi** [comment]
Up still waiting for Laravel 10 support

**Comment by itsourov** [comment]
Waiting

**Comment by superoleg** [comment]
Waiting =)

**Comment by itsourov** [comment]
Temporary solution :

- In your Laravel project `composer.json`, add this

```
{
...
    "require": {
        "unisharp/laravel-filemanager": "dev-master"
    },
    ...
    "repositories": [
        {
          "url": "https://github.com/itsourov/laravel-filemanager.git",
           "type": "git"
        }
    ]
...
}
```

- Then in command line, type `composer install` or `composer update` should do the job.

Please noted that if not change the `unisharp/laravel-filemanager` version to `dev-master` the composer will install the official version instead of local repository one.

Credit: @weiliang79

**Comment by streamtw** [comment]
Laravel 10 support has been added in `v2.6.0`. Thanks to @weiliang79 .
