### ISSUE TITLE
laravel 5.3 /photos/ route 404

### ISSUE THREAD

**Issue by ThePoet444** [UniSharp/laravel-filemanager#129]
I edited the config so images_dir points to storage/image and made it writeable. Images get uploaded fine. However when it comes time to view the images it's looking to /photos/{id}/{filename} .. and it's getting a 404. the user id and filename get generated correctly, but the route to /photos is a 404.

**Comment by leanweb** [comment]
Storage is not in the public directory... it is above the root of the app http://yourapp.com = public directory...

**Comment by ThePoet444** [comment]
So the only way this package works is if I store all the pics and files in the public directory. That's not very useful for my project. Is there any way I can make this work with a non-public directory?

**Comment by leanweb** [comment]
Don't shoot the messenger... I am just trying to help... I am not the author, just a user like you... 

Now, you realize that in order to serve images from a private directory, you would have to modify the the code to use a route for the resource... sort of like create a route Route::get('image/{image}/view', 'ImageResourceController@getimage') ... and in your controller build the response by hand with the response object, build the header yourself and return the file... Not a huge task, but could be a nice add on to this project... 

I think there is another thread about this...

**Comment by g0110280** [comment]
@ThePoet444 We haven't support this feature for now. It's in our [v2.0 milestone](https://github.com/UniSharp/laravel-filemanager/milestone/6). Feel free to make pull request =)

**Comment by g0110280** [comment]
Related to #115 , close issue for now.
