### ISSUE TITLE
Change CDN loaded front vendor to local ones

### ISSUE THREAD

**Issue by welcoMattic** [UniSharp/laravel-filemanager#16]
I think it's better to build package own `vendors.js` and `vendors.css` files to avoid to load each vendors file from a CDN.

We can reduce HTTP request and filemanager window loading time :wink: 

Maybe use Bower and a small gulpfile to build it?

**Comment by youchenlee** [comment]
But thus we lost the benefit of using CDN. (better cache / lower latency / lower server loading)

Since the HTTP connection is parallel, it might not be a problem. If there is a single CDN provider having a big latency to France (or somewhere to your users), we could consider changing it to a faster provider.

**Comment by youchenlee** [comment]
If no further discussion, I will close this issue in 3 days.

**Comment by skid9000** [comment]
Please reconsider the issue.

There are a lot of case where you don't want to have CDNs in your app (offline env, privacy concerns, etc...), so at least provide the option to have the CDN resources self hosted.
