### ISSUE TITLE
Any possible way to disable authentication to the file manage in a development stage

### ISSUE THREAD

**Issue by kfulk14** [UniSharp/laravel-filemanager#162]
I was wondering if their was anyway to temp disable all authentication to the file manager while I am testing my app in my development server.

**Comment by g0110280** [comment]
No such config for now. There is an example image named `sleeping-dog.jpg` in `laravel-filemanager/public/images/test-folder/`, you can upload this image for your test.

**Comment by g0110280** [comment]
To disable user authentication, set `middlewares` to empty array in `config/lfm.php`.

**Comment by ankitkbl** [comment]
there is no middleware in config/lfm.php. still getting same issue

**Comment by Jaikumar0101** [comment]
I have found a method to remove middleware but you should put admin auth etc in that rather than remove auth middleware otherwise works fine
Here is the solution :-)
------------------------------------------------
 UniSharp\LaravelFilemanager\LaravelFilemanagerServiceProvider::class,
 You go to the LaravelFilemanagerServiceProvider.php and change middleware there and remove auth middleware from middlewares

![image](https://user-images.githubusercontent.com/89125772/160046508-9d678579-8b89-4dc3-bc50-0b6606cfa458.png)
