### ISSUE TITLE
"Undefined variable: working_dir" when trying to upload an image

### ISSUE THREAD

**Issue by isinkler** [UniSharp/laravel-filemanager#250]
I'm using TinyMCE with Laravel 5.2, and when I click on the image upload button, this error appears:

> ErrorException in 7d7f0959690b68b0f0aaac97e94cffad0caddec6.php line 129:
Undefined variable: working_dir

Please help me fix this!

**Comment by GregKeaney** [comment]
Perhaps not related but I just mysteriously started getting this error;

ErrorException in 779d4a430477bdafd67cfb6a93f1dd698ef17d4f.php line 29:
Undefined variable: extension_not_found

**Comment by GregKeaney** [comment]
Again, not sure if this helps but I looked closer and my config/lfm.php was NOT the same as the docs suggested.  Very odd as this package has been in my app since Jan and working.  In any case I upgraded to the latest stable version following this - https://unisharp.github.io/laravel-filemanager/upgrade.
Seems all good now.

**Comment by isinkler** [comment]
@GregKeaney Thank you, that was the problem.

**Comment by GregKeaney** [comment]
Coolio.

**Comment by g0110280** [comment]
Thank you @GregKeaney .
