### ISSUE TITLE
Images not uploading, files do work

### ISSUE THREAD

**Issue by intergalactisch** [UniSharp/laravel-filemanager#306]
Hi, after the upgrade (and eventually a clean install) of the Laravel Filemanager I can't seem to upload an image (.png and .jpg both don't work). However, files (.txt, .doc) do work without a problem. With this I am using the default Laravel structure (so /public as documentRoot) and have CHMOD and CHOWN all the proper folders.

Any idea what is going wrong and what I can try to make this work? I don't see any errors in console and everything else seems to be loading perfectly fine. Also, previous versions where working really well.

This is the output of php ./vendor/unisharp/laravel-filemanager/bin/debug.

OS System & Version: Linux SERVERNAMESTUFF.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64
Laravel Version: v5.3.31
File Manager Version: v1.7.6
imagick Extension: Install
gd Extension: Install

**Comment by PendoNL** [comment]
Did you update the filemanager lately? You may want to look at the new config file, there are a few new settings. One of them being a memory_limit in the config file that get's increased before uploads. Most issues lately for not being able to update are caused by memory limits being hit.

See this file and line for what I mean: https://github.com/UniSharp/laravel-filemanager/blob/master/src/config/lfm.php#L167, I increased this to 512M myself and I hardly get any errors since. It's still an issue sometimes, but that's due to GD and not caused by laravel-filemanager.

**Comment by intergalactisch** [comment]
THanks, but unfortunately this didn't solve the problem. I still can't upload images, but it doesn't show me why...no console errors, no Exceptions, nothing :(

**Comment by PendoNL** [comment]
Does it looks like it's working, but nothing is uploaded? Can you check your console, there should be a request to an /upload route. You may want to check if the response there is "OK". 

I tested with both GD en Imagick, when using Imagick I got an "OK" response but no file was uploaded. When using GD it worked, but only after I enabled `exif`. The upload script from laravel-filemanger tries to rotate the image based on it's orientation. Without exif this fails and nothing is being returned as upload (while the response is still "OK").

**Comment by intergalactisch** [comment]
Yay, enabling EXIF worked! Awesome, thanks!

**Comment by HashTech4u** [comment]
I tried every thing  on my ubunut 16.04 from permission to downgrade/upgrade lfm. but problem was still there. I was able to upload a file but no success in image uploads. i also installed EXIF, but after trying every thing when i installed PHP-GD by sudo apt-get install php7.0-gd   it solved my problem.
