### ISSUE TITLE
Can't Upload Large files

### ISSUE THREAD

**Issue by jonjie0317** [UniSharp/laravel-filemanager#312]
I can't upload large file size. I just can upload 18MB as maximum. I've also change the `'max_file_size' => 900000,` in `lfm.php`, but still not working.<br><br>

Thanks.

**Comment by gwleuverink** [comment]
max_file_size is one of the few ini settings that cannot be changed this way. The ini overrides are applied on every request, so on the same request you try to upload a large file you also override the max_file_size option. Which is too late.

Try and change this in you actual .ini file.

I think this detail should be documented by the way. Is there any way I can contribute this to the Github pages documentation?  @g0110280

**Comment by g0110280** [comment]
Thank you @gwleuverink , documents are in [here](https://github.com/UniSharp/laravel-filemanager/tree/master/docs).

**Comment by jonjie0317** [comment]
@gwleuverink @g0110280  hm, so, what should I do guys? to set the size of the file? <br><br>
Thanks

**Comment by gwleuverink** [comment]
You can try to edit your php.ini file on the server you are running this on and then restart php for the changes to take effect.

If you have ssh access to your server the procedure is quite simple. [This guide](https://nl.godaddy.com/help/increasing-user-file-upload-limits-using-phpini-on-your-linux-server-1409) should do the trick.

**Comment by jonjie0317** [comment]
@gwleuverink is there any way to do this, just by using this package?

**Comment by gwleuverink** [comment]
I believe it is technically impossible to override an ini setting expanding the post size in the same request you are doing the post, since the large request is already sent before the override takes effect.

The function that is used for overriding is [ini_set()](http://php.net/manual/en/function.ini-set.php)

The php documentation states that any settings applied this way are restored after the script is done executing. So what you need is not possible using this method. You **have** to change the php.ini file on the server you are running this on.

If you don't have ssh access because you are on shared hosting it is usually possible to do this within the your hosting provider's dashboard.

**Comment by jonjie0317** [comment]
@gwleuverink hm, thanks men. I'll change ini setting for now. Hm, one more thing, Im so sorry if I have a lot of questions, just confused. What would `'max_image_size' => 50000`, `'max_file_size' => 50000`, and, `'memory_limit'        => '256M'` for? <br><br>
Thanks much

**Comment by gwleuverink** [comment]
No problem. You can basically see this as a configuration file that dictates how this particular php install should work. You can finetune these settings according to the requirements of your app.

* memory_limit is a directive that dictates how many bytes are allocated to the php process to execute it's scripts. (Intervention/image uses a lot of memory, that's why this setting is configured by default)
* upload_max_filesize (what I think you mean by 'max_file_size') dictates the maximum size of of the $_FILES superglobal, which is used to pass files from the browser to the server.
* max_image_size Isn't a configuration option as far as I know.

Many directives exist to finetune your PHP configuration. You can refer to [this](http://php.net/manual/en/ini.core.php) page of the PHP docs to see all options available and for a more comprehensive explanation of the directives you mentioned.

**Comment by jonjie0317** [comment]
oh, thanks a lot men.
