### ISSUE TITLE
Configurable regex for file and folder names.

### ISSUE THREAD

**Issue by domialex** [UniSharp/laravel-filemanager#420]
Do you think you could allow in **lfm.php** to manually specify our own regex for the folder name check?
I wanted to be able to allow spaces, without modifying the source files. The regex _'/[^\w-]/i'_ is used in **FolderController** and **RenameController**.
Also, the regex _'/[^A-Za-z0-9\-\']/'_ for the files could also be replaced in **lfm.php**.
Another solution would be to specify our own function to check and rename files and folders.

**Comment by gwleuverink** [comment]
I get what you are saying. Sounds like a good addition. 

If this feature makes the `alphanumeric_directory` and `alphanumeric_filename` options in **lfm.php** are a little redundant since this feature can do exactly the same and more. Can those two config values be removed or keep it in for backwards compatibility? 
@g0110280 Any thoughts?

**Comment by g0110280** [comment]
Maybe we can make it possible to let users modify the rule from `LfmConfigHandler`. And I suggest we can only leave one config like `regex_check` to toggle this behavior.
