### ISSUE TITLE
do not upload any file to windows server but response uploaded successfully 

### ISSUE THREAD

**Issue by mohaphez** [UniSharp/laravel-filemanager#421]
hi i use last version laravel file manager.
This package is working well in localhost on linux. but when upload the project to windows server
 file manager do not upload any file and response uploaded successfully
I tryed to install php_mbstring / php_exif and enable those
but not changed any thing
debug result :
OS System & Version: Windows NT WIN-1B2A4C8PTET 10.0 build 14393 (Windows Server 2016) i586 Laravel Version: v5.4.36                                                                    File Manager Version: v1.8.1                                                                imagick Extension: Not Install                                                              gd Extension: Install

**Comment by FreedomKnight** [comment]
what kind http server you use? IIS or apache?
You can check MAX_FILE_SIZE in php.ini and server configuration.
Maybe your upload file size is more than that.

**Comment by mohaphez** [comment]
i use IIS for run website.
upload_max_filesize in php.ini is 10M 
i uploaded 135 kb png image but not uploaded and saved in server and return response uploaded successfully

**Comment by vDiFoung** [comment]
Some body please tell me how to fix it ;)

**Comment by mideal** [comment]
I have the same problem on Ubuntu 16 with php 7 and nginx
On local server(xampp) image upload, but on production(ubuntu) server file manager do not upload image and response uploaded successfully. File upload, problem just with image

**Comment by vDiFoung** [comment]
Hello. First, sorry for my English because I'm not American or British ....

10 hours ago, i have the same problem, id use IIS ( if is Xampp you can idetify ) and i fix like this: 
Go to php.ini file , press Ctrl+F, search: upload_tmp_dir, it like this : upload_tmp_dir = C:\Windows\Temp 
After go to path C:\Windows found folder Temp right click Properties -> select Security -> Edit -> Add-> Advanced -> Find now -> press Ctrl to select both IIS_IUSRS and IUSR ( or only IUSR, i have not try yet ). -> OK ->OK -> Now, look into  Group or user names , select one by one ,IIS_IUSRS and IUSR and tick Fullcontrol within Permissions for Creator owner dashboard and Apply -> OK. 
Now, upload try again!
 Trịnh Xuân Việt 27/11/93 Bắc Giang

**Comment by vDiFoung** [comment]
Hello. First, sorry for my English because I'm not American or British ....

10 hours ago, i have the same problem, id use IIS ( if is Xampp you can idetify ) and i fix like this:
Go to php.ini file , press Ctrl+F, search: upload_tmp_dir, it like this : upload_tmp_dir = C:\Windows\Temp
After go to path C:\Windows found folder Temp right click Properties -> select Security -> Edit -> Add-> Advanced -> Find now -> press Ctrl to select both IIS_IUSRS and IUSR ( or only IUSR, i have not try yet ). -> OK ->OK -> Now, look into Group or user names , select one by one ,IIS_IUSRS and IUSR and tick Fullcontrol within Permissions for Creator owner dashboard and Apply -> OK.
Now, upload try again!
                                                                                                      Trịnh Xuân Việt 27/11/93 Bắc Giang

**Comment by FreedomKnight** [comment]
thank you @vDiFoung  maybe @mohaphez you can try it to fix this security proplem

**Comment by vDiFoung** [comment]
Hello. First, sorry for my English because I'm not American or British ....

10 hours ago, i have the same problem, id use IIS ( if use Xampp you can try idetify, just  chage path same within php.ini ) and i fix like this:
Go to php.ini file , press Ctrl+F, search: upload_tmp_dir, it like this : upload_tmp_dir = C:\Windows\Temp
After go to path C:\Windows found folder Temp right click Properties -> select Security -> Edit -> Add-> Advanced -> Find now -> press Ctrl to select both IIS_IUSRS and IUSR ( or only IUSR, i have not try yet ). -> OK ->OK -> Now, look into Group or user names , select one by one ,IIS_IUSRS and IUSR and tick Fullcontrol within Permissions for Creator owner dashboard and Apply -> OK.
Now, upload try again!
Hope it helps you
                                                                                                      Trịnh Xuân Việt 27/11/93 Bắc Giang

**Comment by mohaphez** [comment]
Hi 
thank you about  your  complete description for fix this issue :D 
Incidentally, I also managed to solve this problem today.
I wanted to share the answer, that I saw You have responded sooner.
Anyway, your answer is correct
Thank you @vDiFoung ,@mohaphez :)
And sorry for speaking bad English :|
