### ISSUE TITLE
Filemanager is looking for local files and folders on a production env.

### ISSUE THREAD

**Issue by innoflyweb** [UniSharp/laravel-filemanager#597]
Hi,

I have no idea how to repo this issue. The problem is that i have everything working on my local env, i have some test folder created and some images uploaded. I deployed my app with deployer.phar and when i open laravel-filemanager i get this error:

![image](https://user-images.githubusercontent.com/34184401/39938422-97c14f30-555b-11e8-96f1-89c6c974ab83.png)

It seems to be looking for the folder and images that i uploaded on my local env, but it's a fresh install and separate env. Did i commit something to git that i shouldn't have? How does it now to look for that folder? It could also be a bug so i posted here, if it's not i can also turn to SO. Thanks for any kind of help.

Laravel verison: 5.6.5
Local env: Mac OS 10.13.4
Production env: Ubuntu 17.10

**Comment by gwleuverink** [comment]
Did you use the laravel recipe for deployer? You might have to clear the config cache using

after('deploy:update_code', 'artisan:config:cache');

In deployer.php

Please let me know if that helps. It is weird that your local env variables are run tough. Are you ignoring your local .env and cache directory in .gitignore?

Unrelated to your issue. Have you set the folder you use for the filemanager up as a shared directory within deployer.php? You might overwrite user uploaded files on a deploy otherwise.

**Comment by innoflyweb** [comment]
Yes i'm using laravel recipe and the artisan:config:cache command is built in to that. .env file is also ignored in .gitignore and the storage/framework/cache is ignored by laravel itself. I have also set the the shared dir in deploy.php. Nothing seems to work.

**Comment by innoflyweb** [comment]
Guess it was the usual "Turn it off and then on again" thing. Removed LFM from local and all the related files from git. Also readded the public folder to git and deployed again and now it works.
