### ISSUE TITLE
Invasão Hacker

### ISSUE THREAD

**Issue by luizmagao** [UniSharp/laravel-filemanager#639]
Sofremos uma invasão HACKER pelo **laravel-filemanager** gostaríamos de entender como ser proteger usando o mesmo plugin;

Please check the following instructions before submitting a bug :
 * Make sure you are using the latest version.
 * Make sure you read [installation](http://unisharp.github.io/laravel-filemanager/installation), [integration](http://unisharp.github.io/laravel-filemanager/integration), and [upgrade](http://unisharp.github.io/laravel-filemanager/upgrade) document.

And provide the followings :
 * Operating system :
 * Laravel version :
 * Package version :
 * Steps to reproduce your issue :
 * Screenshots of browser console :

**Comment by gwleuverink** [comment]
Hi @luizmagao Can you post all following communication in English please? I google translated your question:

> We suffered a HACKER invasion by laravel-filemanager we would like to understand how to be protect using the same plugin;

Of course this is a bad thing. The question 'how' exactly I cannot answer with no information about the nature of the hack, directory permissions & ownership of your publicly stored files, configuration you used et cetera.

If you are certain a vulnerability was exposed because of this package please let us know as soon and as detailed as possible so we can make a patch.

**Comment by luizmagao** [comment]
Já resolvi, mudamos o editor. Obrigado.!!
